name: Test

on: [ push , pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Assemble with Gradle
        run: ./gradlew assemble
      - name: Test
        run: ./gradlew test
      - name: Repeat 1
        run: ./gradlew test
      - name: Repeat 2
        run: ./gradlew test
      - name: Repeat 3
        run: ./gradlew test
      - name: Repeat 4
        run: ./gradlew test